<testsuite tests="1"><testcase classname=" python Pota_orches.py sudo python3 DeviceComp.py " name="python Pota_orches.py sudo python3 DeviceComp.py"><failure type="NA">'  File Pota_orches.py, line 36, in &lt;module&gt;
', '
', '    main()
', '
', '  File Pota_orches.py, line 27, in main
', '
', '    client.connect(34.207.194.93, 443)
', '
', '  File C:\Program Files\Python35\lib\site-packages\paho\mqtt\client.py, line 686, in connect
', '
', '    return self.reconnect()
', '
', '  File C:\Program Files\Python35\lib\site-packages\paho\mqtt\client.py, line 808, in reconnect
', '
', '    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
', '
', '  File C:\Program Files\Python35\lib\socket.py, line 711, in create_connection
', '
', '    raise err
', '
', '  File C:\Program Files\Python35\lib\socket.py, line 702, in create_connection
', '
', '    sock.connect(sa)
', '
', 'ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
', '
'</failure></testcase></testsuite>